[package]
name = "cratery"
version = "1.12.0"
authors = ["Laurent Wouters <lwouters@cenotelie.fr>"]
description = "Cratery -- a private cargo registry"
repository = "https://github.com/cenotelie/cratery"
homepage = "https://github.com/cenotelie/cratery"
documentation = "https://github.com/cenotelie/cratery"
license = "MIT"
edition = "2024"

[dependencies]
# logging
fern = "0.7"
log = "0.4"

# serde
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# basic dependencies
base64 = "0.22"
byteorder = "1.5"
bytes = "1.10"
chrono = { version = "0.4", features = ["serde"] }
cookie = { version = "0.18", features = ["percent-encode", "secure"] }
data-encoding = "2.9"
flate2 = "1.1"
http-body = "1"
mime = "0.3"
opendal = { version = "0.54", features = ["services-fs", "services-s3"] }
quick-xml = "0.38"
rand = "0.9"
ring = "0.17"
semver = { version = "1.0", features = ["serde"] }
tar = "0.4"
urlencoding = "2.1"
uuid = { version = "1.18", features = ["fast-rng", "v4"] }

# async support
futures = "0.3"
tokio = { version = "1.47", features = ["full"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["io"] }

# framework for the application
axum = { version = "0.8", features = ["http2", "ws"] }
lettre = { version = "0.11", default-features = false, features = [
    "builder",
    "rustls-tls",
    "smtp-transport",
    "tokio1",
    "tokio1-rustls-tls",
] }
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "rustls-tls-native-roots",
    "stream",
] }
sqlx = { version = "0.8", default-features = false, features = [
    "chrono",
    "macros",
    "runtime-tokio-rustls",
    "sqlite",
] }
tokio-tungstenite = "0.27"

[lints.rust]
# missing_docs = "deny"
unsafe_code = "forbid"
unused_imports = "deny"

[lints.clippy]
#cargo = { priority = -1, level = "warn" }
complexity = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
perf = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
# The individually activated lints below come from : nursery, pedantic, restriction or suspicious.
bind_instead_of_map = "deny"
type_repetition_in_bounds = "deny"
borrowed_box = "deny"
cast_lossless = "deny"
cast_possible_wrap = "deny"
checked_conversions = "deny"
clone_on_copy = "deny"
derive_partial_eq_without_eq = "deny"
doc_markdown = "deny"
explicit_deref_methods = "deny"
extra_unused_lifetimes = "deny"
fallible_impl_from = "warn"
future_not_send = "deny"
if_not_else = "deny"
infinite_loop = "warn"
manual_assert = "deny"
map_unwrap_or = "deny"
match_same_arms = "deny"
missing_const_for_fn = "deny"
missing_errors_doc = "allow"
missing_fields_in_debug = "deny"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "deny"
needless_collect = "deny"
needless_pass_by_ref_mut = "deny"
needless_pass_by_value = "deny"
nonminimal_bool = "deny"
option_if_let_else = "deny"
or_fun_call = "deny"
redundant_closure_for_method_calls = "deny"
semicolon_if_nothing_returned = "deny"
string_lit_as_bytes = "warn"
trivially_copy_pass_by_ref = "deny"
type-repetition-in-bounds = "deny"
uninlined_format_args = "deny"
unreadable_literal = "deny"
use_self = "deny"
useless_conversion = "deny"
