[package]
name = "cratery"
version = "1.13.0"
authors = ["Laurent Wouters <lwouters@cenotelie.fr>"]
edition = "2024"
description = "Cratery -- a private cargo registry"
documentation = "https://github.com/cenotelie/cratery"
homepage = "https://github.com/cenotelie/cratery"
repository = "https://github.com/cenotelie/cratery"
license = "MIT"
keywords = ["cargo", "crates", "private", "registry", "service"]
categories = ["development-tools"]

[dependencies]
# logging
fern = "0.7"
log = "0.4"

# serde
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# basic dependencies
base64 = "0.22"
byteorder = "1.5"
bytes = "1.11"
chrono = { version = "0.4", features = ["serde"] }
cookie = { version = "0.18", features = ["percent-encode", "secure"] }
data-encoding = "2.10"
flate2 = "1.1"
http-body = "1"
opendal = { version = "0.58", features = ["services-fs", "services-s3"] }
rand = "0.9"
ring = "0.17"
semver = { version = "1.0", features = ["serde"] }
tar = "0.4"
urlencoding = "2.1"
uuid = { version = "1.19", features = ["fast-rng", "v4"] }

# async support
futures = "0.3"
tokio = { version = "1.49", default-features = false, features = [
    "process",
    "signal",
] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["io"] }

# framework for the application
axum = { version = "0.8", features = ["http2", "ws"] }
lettre = { version = "0.11", default-features = false, features = [
    "builder",
    "rustls-tls",
    "smtp-transport",
    "tokio1",
    "tokio1-rustls-tls",
] }
reqwest = { version = "0.13", default-features = false, features = [
    "form",
    "rustls",
    "stream",
] }
sqlx = { version = "0.8", default-features = false, features = [
    "chrono",
    "macros",
    "runtime-tokio-rustls",
    "sqlite",
] }
tokio-tungstenite = "0.28"

[lints.rust]
broken_intra_doc_links = "warn"
missing_crate_level_docs = "warn"
unsafe_code = "forbid"
unused_imports = "warn"

[lints.clippy]
cargo = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
correctness = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
# The individually activated lints below come from : nursery, restriction.
allow_attributes = "warn"
as_ptr_cast_mut = "warn"
await_holding_lock = "warn"
bool_to_int_with_if = "warn"
branches_sharing_code = "warn"
cast_lossless = "warn"
char_lit_as_u8 = "warn"
checked_conversions = "warn"
clear_with_drain = "warn"
cloned_instead_of_copied = "warn"
collection_is_never_read = "warn"
dbg_macro = "warn"
debug_assert_with_mut_call = "warn"
default_union_representation = "warn"
derive_partial_eq_without_eq = "warn"
disallowed_macros = "warn"
disallowed_methods = "warn"
disallowed_names = "warn"
disallowed_script_idents = "warn"
disallowed_types = "warn"
doc_link_with_quotes = "warn"
doc_markdown = "warn"
empty_enum = "warn"
empty_enum_variants_with_brackets = "warn"
empty_line_after_outer_attr = "warn"
enum_glob_use = "warn"
equatable_if_let = "warn"
exit = "warn"
expl_impl_clone_on_copy = "warn"
explicit_deref_methods = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
fallible_impl_from = "warn"
filter_map_next = "warn"
flat_map_option = "warn"
float_cmp_const = "warn"
fn_params_excessive_bools = "warn"
fn_to_numeric_cast_any = "warn"
from_iter_instead_of_collect = "warn"
future_not_send = "deny"
get_unwrap = "warn"
if_let_mutex = "warn"
implicit_clone = "warn"
implied_bounds_in_impls = "warn"
imprecise_flops = "warn"
index_refutable_slice = "warn"
indexing_slicing = "warn"
inefficient_to_string = "warn"
infinite_loop = "warn"
missing_const_for_fn = "warn"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "warn"
mixed_attributes_style = "warn"
#mod_module_files = "warn"
module_name_repetitions = "allow"
multiple_crate_versions = "allow"
needless_collect = "deny"
needless_pass_by_ref_mut = "deny"
option_if_let_else = "warn"
or_fun_call = "deny"
significant_drop_tightening = "warn"
string_lit_as_bytes = "warn"
string_to_string = "warn"
too_long_first_doc_paragraph = "warn"
type_repetition_in_bounds = "deny"
unneeded-field-pattern = "warn"
unused_trait_names = "warn"
#unwrap_used = "warn"
use_self = "warn"
useless_let_if_seq = "warn"
useless_transmute = "warn"
verbose_file_reads = "warn"
wildcard_dependencies = "warn"
wildcard_enum_match_arm = "warn"
wildcard_imports = "warn"
zero_sized_map_values = "warn"
