name: CI

on:
  push:
    branches-ignore:
      - 'wip*'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v2
      with:
          log-level: warn
          command: check
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Check fmt
      run: cargo fmt --check
    - name: "Check Cargo.toml format"
      uses: gwen-lg/taplo@2d6790a640dea6489fc6db990485d263103d3f05
      with:
        format: true
        format_write_changes: true
        lint: false
    - name: Check spelling
      uses: crate-ci/typos@master
    - name: Lint
      run: cargo clippy --locked
    - name: Run tests
      run: cargo test --locked
