# Required configuration for forks:
# To enable Docker builds, configure the following in "Settings > Secrets and variables > Actions":
# - ENABLE_DOCKER_BUILD (Variable): Set to "true"
# - DOCKERHUB_USERNAME (Variable): Your Docker Hub username
# - DOCKERHUB_TOKEN (Secret): Your Docker Hub personal access token

name: Docker Build and Push

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      build_target:
        description: "Build target"
        required: true
        default: "Release"
        type: choice
        options:
          - Release
          - Debug

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: vars.ENABLE_DOCKER_BUILD == 'true'
    steps:
      - uses: actions/checkout@v7
      - name: Generate Docker Tags and Build Args
        id: gen_docker_tags_list_and_build_args
        env:
          INPUT_BUILD_TARGET: "${{ github.event.inputs.build_target || 'Release' }}"
          DOCKERHUB_USERNAME: "${{ vars.DOCKERHUB_USERNAME }}"
        run: ./.github/scripts/docker-build.sh

      - uses: docker/setup-buildx-action@v4
      - uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            BUILD_FLAGS=${{ steps.gen_docker_tags_list_and_build_args.outputs.build_flags }}
            BUILD_TARGET=${{ steps.gen_docker_tags_list_and_build_args.outputs.build_target }}
          tags: "${{ steps.gen_docker_tags_list_and_build_args.outputs.tags_list }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
